name: Morning Bot ☀️

on:
  schedule:
    - cron: "0 4 * * *"   # این یعنی هر روز ساعت 07:30 صبح ایران (توضیح پایین)
  workflow_dispatch:       # برای اجرای دستی از GitHub هم

jobs:
  send_morning_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests jdatetime

      - name: Run morning bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python "صبح بخیر لحظه ای.py"
