name: Run Morning Bot

on:
  schedule:
    - cron: "00 4 * * *"  # اجرای خودکار هر روز ساعت 07:30 صبح به وقت ایران (UTC+3:30)
  workflow_dispatch:      # اجرا دستی هم ممکن است

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests jdatetime

      - name: Run bot
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python "صبح بخیر لحظه ای.py"
